### ISSUE TITLE
Automate website updates using GitHub Action

### ISSUE THREAD

**Issue by amyheather** [coding-for-reproducible-research/CfRR_Courses#97]
If desired, you could add a GitHub action so that the JupyterBook hosted on GitHub pages is automatically updated with pushes to the main branch. (This may or may not be a feature you might want though!)

I've copied an example of an action that I set up to do this purpose for [our team website](https://github.com/penchord/web/blob/main/.github/workflows/deploy-book.yaml):

```
name: Update GitHub pages
run-name: Create Jupyter Book and publish on GitHub pages

# Source: https://quarto.org/docs/publishing/github-pages.html

on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      
      - name: Install python and dependencies
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: pip install -r requirements.txt

      - name: Build book
        run: |
          jupyter-book build .

      - name: Publish on GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build/html
```
